server:
  listen: 8000
  workers: 4
  upstreams:
    - id: "node1"
      url: "http://localhost:8001"

    - id: "node2"
      url: "http://localhost:8002"


  headers:
    - key: "x-forwarded-for"
      value: "Nginx"    

    - key: "Authorization"
      value: "Bearer xyz"  

  rules:
    - path: /
      upstream: 
        - node1
        - node2

    - path: /admin
      upstream: 
        - node2 